### PR TITLE
Fix: `disallowSpaceAfterKeywords` - fix issue with using default keyword list

### LINKED ISSUE #1885: `return` should not be in the list of `spacedKeywords`, `function` also has an issue
Hello,

I'm running JSCS with this rule enabled:
`disallowSpaceAfterKeywords: true`.

As such, JSCS is telling me that this:
`return obj`
should be:
`returnobj`.

Which is obviously invalid.
I expect setting `disallowSpaceAfterKeywords` to `true` to not affect `return` statements.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27517520-return-should-not-be-in-the-list-of-spacedkeywords-function-also-has-an-issue?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by hzoo**
Fixes #1885
Closes gh-1888

cc @Francisc

### CODE REVIEW

File: lib/rules/disallow-space-after-keywords.js [hunk 1]
```diff
@@ -65,8 +67,8 @@ module.exports.prototype = {
         file.iterateTokensByTypeAndValue('Keyword', this._keywords, function(token) {
             var nextToken = file.getNextToken(token);
 
-            // Make an exception if the next token is also a keyword (a space would be required).
-            if (nextToken.type === 'Keyword') {
+            // Make an exception if the next token is not a Punctuator such as a Keyword or Identifier
+            if (nextToken.type !== 'Punctuator') {
```
Comment (hzoo) [inline lib/rules/disallow-space-after-keywords.js]: The previous fix for `else if` was adding `nextToken.type === 'Keyword'`

I was going to check `nextToken.type == 'Identifier'` but I figured maybe this could be better?

@mikesherov

File: lib/rules/disallow-space-after-keywords.js [hunk 2]
```diff
@@ -51,7 +51,9 @@ module.exports.prototype = {
         );
 
         if (keywords === true) {
-            keywords = defaultKeywords;
+            keywords = defaultKeywords.filter(function(keyword) {
+                return ['function', 'return'].indexOf(keyword) === -1;
```
Comment (gibson042) [inline lib/rules/disallow-space-after-keywords.js]: I would say it's more complicated than this... some keywords require immediately following parentheses (`if`, `for`, `catch`, etc.), intervening whitespace of which can always be removed. Others (`return`, `throw`, `function`, etc.) require whitespace only when necessary to separate them from keywords/identifiers (so `return[]` and `function(){}` are fine but `thrownewError()` and `returnfoo` and `functionbar(){}` aren't). I think you want to leverage and maybe extend/expose more of https://github.com/hzoo/node-jscs/blob/1885/lib/token-categorizer.js , which also deals with such cases (cf. its top-level regular expressions). But you _definitely_ don't want to ignore these keywords outright.

Comment (hzoo) [inline lib/rules/disallow-space-after-keywords.js]: Oops actually I mean't to remove this after changing `nextToken.type !== 'Punctuator'`

**Comment by hzoo** [comment]
@gibson042 what do you think after removing that snippet?

File: lib/rules/disallow-space-after-keywords.js (hunk 2 above)
Comment (hzoo) [inline lib/rules/disallow-space-after-keywords.js]: Although actually - maybe it shouldn't check `function` since we have different rules to check function spacing - and other stuff like `function *` which should be a rule

Comment (hzoo) [inline lib/rules/disallow-space-after-keywords.js]: Yeah even in the example it only has a few keywords (the ones that initially make sense) - not every single keyword. `if, else, for, while, do, switch, try, catch, finally` sound good

**Comment by gibson042** [comment]
I think there are still a few edge cases around [ASI-restricted keywords](http://www.ecma-international.org/ecma-262/6.0/#sec-rules-of-automatic-semicolon-insertion) and EOF like
```js
// false positive: keyword, line terminator, punctuator
yield
"ignored statement with leading punctuator"
```
and
```js
// false negative: keyword, whitespace, line terminator or EOF, identifier or keyword or EOF
break	// ← tab
undeclared
```

…but they may never come up.
